Repository silverstripe/silverstripe-elemental, pull requests merged in 2018-07, with the labels that each got.

#254 Replace some unit tests with behat tests and make required_extensions explicit in tests
  .editorconfig
  .travis.yml
  behat.yml
  tests/BaseElementTest.php
  tests/Behat/features/block-types-report.feature
  tests/Controllers/ElementSiteTreeFilterSearchTest.php
  tests/ElementControllerTest.php
  tests/ElementalEditorTest.php
  tests/Reports/ElementTypeReportTest.php
  tests/Reports/ElementsInUseReportTest.php
  tests/Src/TestPage.php
Labels: affects/v4

#257 FIX Longer block content summaries in elemental editor now do not break under icon
  client/dist/styles/bundle.css
  client/src/styles/admin.scss
Labels: affects/v4, change/patch, type/frontend

#258 FIX Fix block division by applying margins regardless of screen width
  client/dist/styles/bundle.css
  client/src/styles/history.scss
Labels: affects/v4, change/patch

#262 FIX CMS search now takes frontend themes into account instead of crashing
  src/Controllers/ElementSiteTreeFilterSearch.php
Labels: affects/v4, change/patch

#259 FIX Check canView() permission before rendering BaseElements
  src/Models/ElementalArea.php
  tests/ElementControllerTest.php
  tests/ElementalAreaTest.php
  tests/ElementalAreaTest.yml
  tests/Src/TestElement.php
Labels: affects/v4, change/patch

#260 FIX Elements in use report source list is now lazy loaded allowing for larger data sets
  src/Reports/ElementsInUseReport.php
  tests/Reports/ElementsInUseReportTest.php
Labels: affects/v4, change/patch

#265 FIX Do not try and filter unsaved lists when determining canView permissions
  src/Models/ElementalArea.php
  tests/ElementalAreaTest.php
Labels: affects/v4, change/patch

#274 NEW Add GraphQL query HOC for returning the content blocks on a page
  .editorconfig
  _config/graphql.yml
  client/src/state/editor/readBlocksForPageQuery.js
  package.json
  src/GraphQL/ElementsResolver.php
Labels: affects/v4, change/minor

#277 NEW Query for reading blocks is now bound to ElementEditor component
  client/dist/js/bundle.js
  client/dist/styles/bundle.css
  client/src/boot/registerComponents.js
  client/src/boot/registerTransforms.js
  client/src/components/ElementEditor/Element.js
  client/src/components/ElementEditor/ElementEditor.js
  client/src/components/ElementEditor/ElementList.js
  client/src/components/ElementEditor/Toolbar.js
  client/src/legacy/ElementEditor/entwine.js
  client/src/state/editor/readBlocksForPageQuery.js
  client/src/types/elementType.js
  src/ElementalEditor.php
  templates/DNADesign/Elemental/ElementalEditor.ss
  templates/DNADesign/Elemental/ElementalEditor_holder.ss
Labels: affects/v4, change/minor

#279 FIX Ensure that SiteTree::ElementArea is always available for GraphQL queries
  _config/extensions.yml
  _config/graphql.yml
  client/dist/js/bundle.js
  client/src/state/editor/readBlocksForPageQuery.js
  src/ElementalEditor.php
  src/Extensions/SiteTreeExtension.php
  tests/Extensions/SiteTreeExtensionTest.php
Labels: affects/v4, change/patch

#280 FIX Return empty ElementalArea if none exists for the page
  src/Extensions/SiteTreeExtension.php
Labels: affects/v4, change/patch

#283 DOCS Start upgrade guide for elemental 3 to 4, fix broken image link in readme
  README.md
  docs/en/upgrading_to_4.md
Labels: affects/v4, change/patch, type/docs

#278 Update skeleton Header component
  _config/graphql.yml
  client/dist/js/bundle.js
  client/dist/styles/bundle.css
  client/src/boot/registerComponents.js
  client/src/components/ElementEditor/Content.js
  client/src/components/ElementEditor/Element.js
  client/src/components/ElementEditor/ElementEditor.scss
  client/src/components/ElementEditor/Header.js
  client/src/components/ElementEditor/Header.scss
  client/src/state/editor/readBlocksForPageQuery.js
  client/src/styles/bundle.scss
  client/src/types/elementType.js
  docs/en/upgrading_to_4.md
  package.json
  src/Models/BaseElement.php
Labels: affects/v4, change/minor
