Repository silverstripe/silverstripe-elemental, pull requests merged in 2018-05, with the labels that each got.

#197 Added improvements to rendertemplates
  src/Models/BaseElement.php
Labels: affects/v4, change/minor

#224 Page level history
  _config/config.yml
  client/dist/js/bundle.js
  client/dist/styles/bundle.css
  client/src/boot/index.js
  client/src/boot/registerComponents.js
  client/src/boot/registerTransforms.js
  client/src/bundles/bundle.js
  client/src/components/HistoricElementView/HistoricElementView.js
  client/src/components/HistoricElementView/tests/HistoricElementView-test.js
  client/src/styles/admin.scss
  client/src/styles/history.scss
  package.json
  src/ElementalEditor.php
  src/Forms/ElementalAreaConfig.php
  src/Forms/ElementalAreaField.php
  tests/Forms/ElementalAreaFieldTest.php
  yarn.lock
Labels: affects/v4, change/minor

#230 NEW Revert a version (Block History)
  _config/graphql.yml
  client/dist/js/bundle.js
  client/src/boot/registerTransforms.js
  client/src/state/history/readOneBlockQuery.js
  client/src/state/history/revertToBlockVersionMutation.js
Labels: affects/v4, type/enhancement

#235 DOCS Delete changelog file
  CHANGELOG.md
Labels: affects/v4, type/docs
