Repository silverstripe/silverstripe-elemental, pull requests merged in 2018-02, with the labels that each got.

#187 FIX Remove the aliased versioned GridFieldState component
  src/ElementalEditor.php
Labels: affects/v4, change/patch, type/UX

#188 NEW Enable elemental content to return its owner page in CMS SiteTree searches
  _config/config.yml
  src/Controllers/ElementSiteTreeFilterSearch.php
  tests/Controllers/ElementSiteTreeFilterSearchTest.php
  tests/Controllers/ElementSiteTreeFilterSearchTest.yml
  tests/Src/TestPage.php
Labels: affects/v4, change/minor

#190 NEW Add circular versioned state indicators to blocks in the elemental GridField
  client/dist/styles/bundle.css
  client/src/styles/admin.scss
  client/src/styles/reports.scss
  src/Models/BaseElement.php
  templates/DNADesign/Elemental/Models/BaseElement/PreviewIcon.ss
Labels: affects/v4, change/minor

#191 Add extension points to BaseElement can() methods.
  src/Models/BaseElement.php
Labels: affects/v4, change/minor, type/enhancement

#193 DOCS More copy/paste friendly instructions
  README.md
Labels: affects/v4, type/docs

#168 Fix edit CMSEditLink when parent is not a page
  src/Models/BaseElement.php
Labels: affects/v4, change/patch

#154 Adds ability to have templates for specific element areas
  src/Models/BaseElement.php
Labels: affects/v4, change/minor
