Repository silverstripe/silverstripe-elemental, pull requests merged in 2018-12, with the labels that each got.

#538 FIX Ensuring redux knows that the form state is now "pristine" when saving in-line
  client/dist/js/bundle.js
  client/src/components/ElementActions/SaveAction.js
Labels: affects/v4, change/patch

#537 FIX always build an ElementalArea for all newly extended classes
  src/Extensions/ElementalAreasExtension.php
Labels: affects/v4, effort/medium, impact/high

#539 DOCS Update userhelp to reflect current UI updates
  docs/en/userguide/_images/banner_example.png
  docs/en/userguide/_images/block_version.png
  docs/en/userguide/_images/content_block_collapsed.png
  docs/en/userguide/_images/content_block_compare.png
  docs/en/userguide/_images/content_block_states.png
  docs/en/userguide/_images/content_block_types.png
  docs/en/userguide/_images/creating_a_content_block.png
  docs/en/userguide/_images/edit_via_more_actions.png
  docs/en/userguide/_images/editing_content.png
  docs/en/userguide/_images/inline_editing.png
  docs/en/userguide/_images/more_options.png
  docs/en/userguide/_images/reorder_blocks.png
  docs/en/userguide/_images/reordering_blocks.png
  docs/en/userguide/_images/tooltip.png
  docs/en/userguide/_images/viewing_block_history.png
  docs/en/userguide/edit_content.md
  docs/en/userguide/history.md
  docs/en/userguide/index.md
  docs/en/userguide/reports.md
Labels: affects/v4, type/UX, type/userhelp

#545 DOCS fix user guide link on readme
  README.md
Labels: affects/v4, type/docs

#546 FIX Add bottom border to empty list container, increase bottom margin and consistent height
  client/dist/styles/bundle.css
  client/src/components/ElementEditor/Element.scss
  client/src/components/ElementEditor/ElementList.scss
Labels: affects/v4, change/patch

#557 FIX Update GraphQL config and CMS dependancy so we support ^4
  _config/graphql.yml
  composer.json
Labels: affects/v4, change/patch

#552 feat(BaseElement): canView on a per element basis
  src/Models/BaseElement.php
Labels: affects/v4, change/minor
