Repository silverstripe/silverstripe-elemental, pull requests merged in 2018-09, with the labels that each got.

#365 Unpublish an element via inline button
  _config/graphql.yml
  client/dist/js/bundle.js
  client/src/components/ElementEditor/Element.js
  client/src/components/ElementEditor/Header.js
  client/src/state/editor/readBlocksForPageQuery.js
  client/src/state/editor/unpublishBlockMutation.js
  client/src/types/elementType.js
  src/Models/BaseElement.php
Labels: affects/v4, type/UX, type/enhancement

#373 NEW Show CMS field (top-level) tabs in more actions dropdown
  _config/cache.yml
  client/dist/js/bundle.js
  client/src/components/ElementEditor/AddElementPopoverContent.js
  client/src/components/ElementEditor/AddNewButton.js
  client/src/components/ElementEditor/Element.js
  client/src/components/ElementEditor/ElementEditor.js
  client/src/components/ElementEditor/ElementList.js
  client/src/components/ElementEditor/Header.js
  client/src/components/ElementEditor/Toolbar.js
  client/src/components/ElementEditor/tests/ElementEditor-test.js
  client/src/components/ElementEditor/tests/Header-test.js
  client/src/types/elementTypeType.js
  src/Forms/ElementalAreaField.php
  src/Services/ElementTabProvider.php
Labels: change/minor, type/enhancement

#375 FIX Updating styling to more accurately match given designs
  client/dist/js/bundle.js
  client/dist/styles/bundle.css
  client/src/components/ElementEditor/Element.js
  client/src/components/ElementEditor/Element.scss
  client/src/components/ElementEditor/Header.js
  client/src/components/ElementEditor/Header.scss
  client/src/components/ElementEditor/Summary.scss
Labels: affects/v4, change/major

#376 FIX Use cachable call to get page version from draft stage
  src/Models/BaseElement.php
  src/Models/ElementalArea.php
Labels: affects/v4, change/patch

#377 FIX Ensure Versioned query has table name prefix so it will work with modules like fluent
  src/Models/ElementalArea.php
Labels: affects/v4, change/patch

#372 Add ability to load Element's edit form inline
  client/dist/js/bundle.js
  client/dist/styles/bundle.css
  client/src/boot/registerComponents.js
  client/src/components/ElementEditor/Content.js
  client/src/components/ElementEditor/Element.js
  client/src/components/ElementEditor/FormBuilder.js
  client/src/components/ElementEditor/FormBuilder.scss
  client/src/components/ElementEditor/InlineEditForm.js
  client/src/components/ElementEditor/InlineEditForm.scss
  client/src/components/ElementEditor/tests/Content-test.js
  client/src/styles/bundle.scss
  src/Controllers/ElementalAreaController.php
  src/Forms/EditFormFactory.php
  src/Models/BaseElement.php
  tests/Behat/Context/FeatureContext.php
  tests/Behat/features/archive-block-element.feature
  tests/Behat/features/edit-block-element.feature
  tests/Behat/features/element-editor.feature
Labels: affects/v4, change/minor

#386 FIX Add namespaces to inline edit form field names
  src/Forms/EditFormFactory.php
  tests/Behat/features/add-block-element.feature
  tests/Behat/features/edit-block-element.feature
  tests/Behat/features/element-editor.feature
  tests/Forms/EditFormFactoryTest.php
  tests/Forms/EditFormFactoryTest.yml
Labels: affects/v4, change/patch

#385 API Move elemental editor actions menu items into their own HOCs
  client/dist/js/bundle.js
  client/src/boot/registerComponents.js
  client/src/boot/registerTransforms.js
  client/src/components/ElementActions/AbstractAction.js
  client/src/components/ElementActions/ArchiveAction.js
  client/src/components/ElementActions/PublishAction.js
  client/src/components/ElementActions/UnpublishAction.js
  client/src/components/ElementActions/tests/AbstractAction-test.js
  client/src/components/ElementActions/tests/ArchiveAction-test.js
  client/src/components/ElementActions/tests/PublishAction-test.js
  client/src/components/ElementActions/tests/UnpublishAction-test.js
  client/src/components/ElementEditor/Content.js
  client/src/components/ElementEditor/ElementActions.js
  client/src/components/ElementEditor/Header.js
  client/src/components/ElementEditor/tests/ElementActions-test.js
  client/src/components/ElementEditor/tests/Header-test.js
Labels: affects/v4, change/major

#393 NEW Add flag to hide the nav tabs in the editable form
  src/Models/BaseElement.php
Labels: affects/v4, change/minor

#400 FIX Removing add block section from the middle of the list
  client/dist/js/bundle.js
  client/src/components/ElementEditor/ElementList.js
Labels: affects/v4, change/patch

#402 NEW Add toast messages when publishing and unpublishing blocks
  client/dist/js/bundle.js
  client/src/components/ElementActions/PublishAction.js
  client/src/components/ElementActions/UnpublishAction.js
  client/src/components/ElementActions/tests/PublishAction-test.js
  client/src/components/ElementActions/tests/UnpublishAction-test.js
  tests/Behat/Context/FeatureContext.php
  tests/Behat/features/publish-block-element.feature
  tests/Behat/features/unpublish-block-element.feature
Labels: affects/v4, change/minor, type/UX

#405 FIX Add types for parameters
  tests/Behat/Context/FeatureContext.php
Labels: affects/v4, change/minor

#406 NEW Refactor AddElementWidget. Add search feature.
  client/dist/js/bundle.js
  client/dist/styles/bundle.css
  client/src/boot/registerComponents.js
  client/src/components/ElementActions/PublishAction.js
  client/src/components/ElementActions/UnpublishAction.js
  client/src/components/ElementActions/tests/PublishAction-test.js
  client/src/components/ElementActions/tests/UnpublishAction-test.js
  client/src/components/ElementEditor/AddElementPopover.js
  client/src/components/ElementEditor/AddElementPopover.scss
  client/src/components/ElementEditor/AddElementPopoverContent.js
  client/src/components/ElementEditor/AddElementPopoverContent.scss
  client/src/components/ElementEditor/AddNewButton.js
  client/src/styles/bundle.scss
  tests/Behat/Context/FeatureContext.php
  tests/Behat/features/publish-block-element.feature
  tests/Behat/features/unpublish-block-element.feature
Labels: affects/v4, change/minor, type/UX, type/enhancement

#392 NEW Add save action to element inline edit forms
  client/dist/js/bundle.js
  client/src/boot/registerTransforms.js
  client/src/components/ElementActions/AbstractAction.js
  client/src/components/ElementActions/ArchiveAction.js
  client/src/components/ElementActions/PublishAction.js
  client/src/components/ElementActions/SaveAction.js
  client/src/components/ElementActions/UnpublishAction.js
  client/src/components/ElementActions/tests/AbstractAction-test.js
  client/src/components/ElementActions/tests/ArchiveAction-test.js
  client/src/components/ElementActions/tests/PublishAction-test.js
  client/src/components/ElementActions/tests/UnpublishAction-test.js
  client/src/components/ElementEditor/Element.js
  client/src/components/ElementEditor/ElementActions.js
  client/src/components/ElementEditor/ElementList.js
  client/src/components/ElementEditor/Header.js
  client/src/components/ElementEditor/InlineEditForm.js
  client/src/state/editor/getSerializedFormData.js
  client/src/state/editor/loadElementSchemaValue.js
  src/Controllers/ElementalAreaController.php
  tests/Behat/features/publish-block-element.feature
  tests/Behat/features/unpublish-block-element.feature
Labels: affects/v4, change/minor

#412 FIX Change toast message for unsuccessful publishing of block
  client/dist/js/bundle.js
  client/src/components/ElementActions/UnpublishAction.js
Labels: affects/v4, change/minor

#411 NEW Add notification on save action
  client/dist/js/bundle.js
  client/src/components/ElementActions/SaveAction.js
Labels: affects/v4, change/minor, type/UX, type/enhancement

#413 FIX Adjust height of buttons in AddElementPopover
  client/dist/styles/bundle.css
  client/src/components/ElementEditor/AddElementPopover.scss
Labels: affects/v4, change/minor, type/UX
