Repository silverstripe/silverstripe-elemental, pull requests merged in 2018-11, with the labels that each got.

#474 FIX Use HOC in admin to create a drag drop context
  client/dist/js/bundle.js
  client/src/components/ElementEditor/ElementEditor.js
  package.json
  yarn.lock
Labels: affects/v4, change/patch, type/bug

#456 FIX Two CMSField fixes (related to UploadField / FileBlock)
  src/Controllers/ElementalAreaController.php
  src/Forms/ElementalAreaField.php
  src/Models/BaseElement.php
Labels: affects/v4, change/patch, type/bug

#488 FIX Reorder text checkbox group and apply Reactstrap styles
  client/dist/js/bundle.js
  client/dist/styles/bundle.css
  client/src/boot/registerComponents.js
  client/src/components/TextCheckboxGroupField/TextCheckboxGroupField.js
  client/src/components/TextCheckboxGroupField/TextCheckboxGroupField.scss
  client/src/styles/bundle.scss
  src/Forms/EditFormFactory.php
  src/Forms/TextCheckboxGroupField.php
  src/Models/BaseElement.php
  yarn.lock
Labels: affects/v4, change/patch, type/UX

#495 NEW Adding a plus icon to the Add Blocks button
  client/dist/js/bundle.js
  client/src/components/ElementEditor/AddNewButton.js
Labels: affects/v4, change/minor

#494 Upgrade to React 16 and latest node.js version
  .travis.yml
  client/dist/js/bundle.js
  client/src/components/ElementActions/AbstractAction.js
  client/src/components/ElementActions/tests/AbstractAction-test.js
  client/src/components/ElementActions/tests/ArchiveAction-test.js
  client/src/components/ElementActions/tests/PublishAction-test.js
  client/src/components/ElementActions/tests/UnpublishAction-test.js
  client/src/components/ElementEditor/AddElementPopover.js
  client/src/components/ElementEditor/AddNewButton.js
  client/src/components/ElementEditor/Content.js
  client/src/components/ElementEditor/Element.js
  client/src/components/ElementEditor/ElementActions.js
  client/src/components/ElementEditor/ElementDragPreview.js
  client/src/components/ElementEditor/ElementEditor.js
  client/src/components/ElementEditor/ElementList.js
  client/src/components/ElementEditor/Header.js
  client/src/components/ElementEditor/HoverBar.js
  client/src/components/ElementEditor/InlineEditForm.js
  client/src/components/ElementEditor/Summary.js
  client/src/components/ElementEditor/Toolbar.js
  client/src/components/ElementEditor/tests/Content-test.js
  client/src/components/ElementEditor/tests/Element-test.js
  client/src/components/ElementEditor/tests/ElementActions-test.js
  client/src/components/ElementEditor/tests/ElementEditor-test.js
  client/src/components/ElementEditor/tests/ElementList-test.js
  client/src/components/ElementEditor/tests/Header-test.js
  client/src/components/ElementEditor/tests/Summary-test.js
  client/src/components/HistoricElementView/tests/HistoricElementView-test.js
  client/src/types/elementType.js
  client/src/types/elementTypeType.js
  package.json
  yarn.lock
Labels: affects/v4, change/minor

#513 replaced static call with specific Class call to avoid sort order errors
  src/Models/BaseElement.php
  tests/BaseElementTest.php
Labels: affects/v4, change/patch

#515 FIX TextCheckboxGroupField should passthrough if it has only one child
  client/dist/js/bundle.js
  client/src/components/TextCheckboxGroupField/TextCheckboxGroupField.js
Labels: affects/v4, change/patch

#500 FIX Block types that are in-line editable will have links to their page on reports
  src/Models/BaseElement.php
  src/Reports/ElementsInUseReport.php
Labels: affects/v4, change/major

#521 NEW Element types are now exposed in config
  _config/graphql.yml
  client/dist/js/bundle.js
  client/src/components/ElementEditor/AddElementPopover.js
  client/src/components/ElementEditor/Element.js
  client/src/components/ElementEditor/ElementActions.js
  client/src/components/ElementEditor/ElementList.js
  client/src/components/ElementEditor/Header.js
  client/src/components/ElementEditor/tests/Element-test.js
  client/src/components/ElementEditor/tests/Header-test.js
  client/src/legacy/ElementEditor/entwine.js
  client/src/state/editor/addElementMutation.js
  client/src/state/editor/elementConfig.js
  client/src/state/editor/readBlocksForPageQuery.js
  client/src/types/elementTypeType.js
  src/Controllers/ElementalAreaController.php
  src/Forms/ElementalAreaField.php
  src/GraphQL/AddElementToAreaMutation.php
  src/GraphQL/SortBlockMutationCreator.php
  src/Models/BaseElement.php
  src/Services/ElementTypeRegistry.php
Labels: affects/v4, change/minor

#501 NEW Using the breadcrumbs API of reports if available
  src/Reports/ElementTypeReport.php
  src/Reports/ElementsInUseReport.php
Labels: affects/v4, change/minor

#523 API Making the read-only version of TextCheckboxGroupField more readable
  client/dist/js/bundle.js
  client/dist/styles/bundle.css
  client/src/components/TextCheckboxGroupField/TextCheckboxGroupField.js
  client/src/components/TextCheckboxGroupField/TextCheckboxGroupField.scss
  src/Forms/ElementalAreaField.php
  src/Forms/TextCheckboxGroupField.php
  src/Models/BaseElement.php
  src/Models/ElementalArea.php
  tests/Forms/TextCheckboxGroupFieldTest.php
Labels: affects/v4, change/major

#532 FIX being able to swap tabs on inline blocks
  client/dist/js/bundle.js
  client/src/components/ElementEditor/ElementActions.js
  client/src/components/ElementEditor/Header.js
Labels: affects/v4, change/patch
