Repository silverstripe/silverstripe-elemental, pull requests merged in 2018-10, with the labels that each got.

#421 NEW Allow adding blocks inline via HoverBar by utilising AddElementPo…
  client/dist/js/bundle.js
  client/dist/styles/bundle.css
  client/src/boot/registerComponents.js
  client/src/components/ElementEditor/AddElementPopover.js
  client/src/components/ElementEditor/AddElementPopover.scss
  client/src/components/ElementEditor/AddNewButton.js
  client/src/components/ElementEditor/ElementEditor.js
  client/src/components/ElementEditor/ElementList.js
  client/src/components/ElementEditor/ElementList.scss
  client/src/components/ElementEditor/HoverBar.js
  client/src/components/ElementEditor/HoverBar.scss
  client/src/components/ElementEditor/Summary.scss
  client/src/components/ElementEditor/tests/ElementList-test.js
  client/src/styles/bundle.scss
Labels: affects/v4, type/UX, type/enhancement

#427 ENHANCEMENT: Writeable local cache API
  src/Models/BaseElement.php
  src/Models/ElementalArea.php
  tests/ElementalAreaTest.php
Labels: affects/v4, change/minor

#432 NEW Treat space key press as mouse click
  client/dist/js/bundle.js
  client/src/components/ElementEditor/Element.js
Labels: affects/v4, change/minor, type/UX, type/bug, type/enhancement

#433 Pulls/4.0/layout annoIEnces
  client/dist/styles/bundle.css
  client/src/components/ElementEditor/HoverBar.scss
Labels: affects/v4, change/patch

#435 MINOR Upgrade Bootstrap to 4.1.2
  client/dist/styles/bundle.css
  package.json
  yarn.lock
Labels: affects/v4, change/minor

#428 NEW Edit tab click changes tab state
  client/dist/js/bundle.js
  client/dist/styles/bundle.css
  client/src/components/ElementActions/AbstractAction.js
  client/src/components/ElementEditor/Content.js
  client/src/components/ElementEditor/Element.js
  client/src/components/ElementEditor/ElementActions.js
  client/src/components/ElementEditor/ElementList.js
  client/src/components/ElementEditor/Header.js
  client/src/components/ElementEditor/Header.scss
  client/src/components/ElementEditor/HoverBar.js
  client/src/components/ElementEditor/InlineEditForm.js
  client/src/components/ElementEditor/tests/ElementActions-test.js
  client/src/components/ElementEditor/tests/ElementEditor-test.js
  client/src/state/editor/loadElementFormStateName.js
  client/src/types/elementTypeType.js
  package.json
  src/Controllers/ElementalAreaController.php
  src/Forms/ElementalAreaField.php
  src/Services/ElementTabProvider.php
  yarn.lock
Labels: affects/v4, type/enhancement

#429 Add mutation to support adding blocks
  _config/graphql.yml
  src/GraphQL/AddElementToAreaMutation.php
  src/GraphQL/SortBlockMutationCreator.php
  src/Services/ReorderElements.php
  tests/GraphQL/AddElementToAreaMutationTest.php
  tests/GraphQL/AddElementToAreaMutationTest.yml
  tests/Services/ElementTabProviderTest.php
  tests/Services/ReorderElementsTest.php
  tests/Services/ReorderElementsTest.yml
Labels: affects/v4, change/minor

#444 FIX Render Content component even if no summary is available
  client/dist/js/bundle.js
  client/src/components/ElementEditor/Content.js
  client/src/components/ElementEditor/tests/Content-test.js
Labels: change/patch, effort/easy, impact/critical, type/bug

#442 FIX Do not write during an elemental owners getCMSFields operation
  src/Extensions/ElementalAreasExtension.php
  src/Models/ElementalArea.php
Labels: affects/v4, change/patch

#397 FIX FormBuilderLoader now keeps its state across remounts so we can remove it rather than hide
  client/dist/js/bundle.js
  client/dist/styles/bundle.css
  client/src/components/ElementEditor/Content.js
  client/src/components/ElementEditor/InlineEditForm.js
  client/src/components/ElementEditor/InlineEditForm.scss
  tests/Behat/features/element-editor.feature
Labels: affects/v4, change/patch

#447 Stop inheritance for disallowed elements
  src/Extensions/ElementalAreasExtension.php
Labels: affects/v4, change/patch

#439 NEW All unsaved blocks on a page will now save as the page is saved
  client/dist/js/bundle.js
  client/src/components/ElementActions/SaveAction.js
  client/src/components/ElementEditor/Element.js
  client/src/components/ElementEditor/ElementEditor.js
  client/src/legacy/ElementEditor/entwine.js
  client/src/state/editor/getSerializedFormData.js
  client/src/state/editor/loadElementFormStateName.js
  src/Forms/ElementalAreaField.php
  tests/Behat/Context/FeatureContext.php
  tests/Behat/Context/FixtureContext.php
  tests/Behat/features/edit-block-element.feature
Labels: affects/v4, change/minor

#459 FIX Replace variable with block type when no title exists
  client/dist/js/bundle.js
  client/src/components/ElementActions/PublishAction.js
  client/src/components/ElementActions/SaveAction.js
  client/src/components/ElementActions/UnpublishAction.js
Labels: affects/v4, change/minor, change/patch, type/UX, type/bug

#449 NEW Don't render InlineEditForm on loadingError
  client/dist/js/bundle.js
  client/src/components/ElementEditor/Content.js
  client/src/components/ElementEditor/Element.js
  client/src/components/ElementEditor/InlineEditForm.js
  src/Controllers/ElementalAreaController.php
Labels: affects/v4, change/patch, type/bug

#462 ENH Add placeholder when no summary content available
  client/dist/js/bundle.js
  client/src/components/ElementEditor/Summary.js
Labels: affects/v4, type/UX, type/enhancement

#461 FIX update page preview after Actioning on an Element
  client/dist/js/bundle.js
  client/src/components/ElementActions/ArchiveAction.js
  client/src/components/ElementActions/PublishAction.js
  client/src/components/ElementActions/SaveAction.js
  client/src/components/ElementActions/UnpublishAction.js
  client/src/components/ElementActions/tests/ArchiveAction-test.js
  client/src/components/ElementEditor/AddElementPopover.js
Labels: affects/v4, change/patch

#464 FIX Bind handleLoadingError in Element constructor
  client/dist/js/bundle.js
  client/src/components/ElementEditor/Element.js
  yarn.lock
Labels: change/patch, type/bug

#471 FIX Return empty String when formState can't be stringified
  client/dist/js/bundle.js
  client/src/components/ElementEditor/ElementEditor.js
Labels: affects/v4, type/bug

#441 NEW Refactor add block popover to use new admin component
  client/dist/js/bundle.js
  client/dist/styles/bundle.css
  client/src/components/ElementEditor/AddElementPopover.js
  client/src/components/ElementEditor/AddElementPopover.scss
  client/src/components/ElementEditor/ElementEditor.js
  client/src/styles/bundle.scss
  tests/Behat/Context/FeatureContext.php
  tests/Behat/features/add-block-element.feature
Labels: affects/v4, change/minor, type/enhancement
