Repository silverstripe/silverstripe-elemental, pull requests merged in 2018-08, with the labels that each got.

#234 updates readme to include other element recommendations
  README.md
Labels: affects/v4, type/docs

#282 Add First, Last, Pos, TotalItems and EvenOdd helpers
  README.md
  src/Models/BaseElement.php
  tests/BaseElementTest.php
  tests/ElementalPageExtensionTest.yml
Labels: affects/v4, change/minor

#284 Element and Content component updates
  _config/graphql.yml
  client/dist/js/bundle.js
  client/dist/styles/bundle.css
  client/src/components/ElementEditor/Content.js
  client/src/components/ElementEditor/Content.scss
  client/src/components/ElementEditor/Element.js
  client/src/components/ElementEditor/Element.scss
  client/src/components/ElementEditor/ElementEditor.js
  client/src/components/ElementEditor/ElementEditor.scss
  client/src/components/ElementEditor/ElementList.js
  client/src/components/ElementEditor/ElementList.scss
  client/src/components/ElementEditor/Header.scss
  client/src/components/ElementEditor/tests/Content-test.js
  client/src/components/ElementEditor/tests/ElementEditor-test.js
  client/src/components/ElementEditor/tests/Header-test.js
  client/src/state/editor/readBlocksForPageQuery.js
  client/src/styles/bundle.scss
  client/src/types/elementType.js
  src/GraphQL/Types/ObjectType.php
  src/Models/BaseElement.php
  src/Models/ElementContent.php
  src/ORM/FieldType/DBObjectType.php
  yarn.lock
Labels: affects/v4, change/minor

#287 Add npm build check and linting to Travis matrix
  .travis.yml
Labels: affects/v4

#281 ADD React version of the elemental add block control
  README.md
  client/dist/js/bundle.js
  client/dist/styles/bundle.css
  client/src/boot/registerComponents.js
  client/src/components/ElementEditor/AddNewButton.js
  client/src/components/ElementEditor/AddNewButton.scss
  client/src/components/ElementEditor/ElementEditor.js
  client/src/components/ElementEditor/ElementEditor.scss
  client/src/components/ElementEditor/ElementList.scss
  client/src/components/ElementEditor/Toolbar.js
  client/src/components/ElementEditor/Toolbar.scss
  client/src/components/ElementEditor/tests/ElementEditor-test.js
  client/src/components/ElementEditor/tests/Header-test.js
  client/src/legacy/ElementEditor/entwine.js
  client/src/styles/bundle.scss
  src/ElementalEditor.php
  src/Extensions/ElementalAreasExtension.php
  src/Forms/ElementalAreaConfig.php
  src/Forms/ElementalAreaField.php
  templates/DNADesign/Elemental/Forms/ElementalAreaField_holder.ss
  tests/ElementalEditorTest.php
  tests/Forms/ElementalAreaFieldTest.php
Labels: affects/v4, change/minor

#302 DOCS Updating upgrade guide to mention removal of ElementEditor and how GridField is used
  docs/en/upgrading_to_4.md
Labels: affects/v4, type/docs

#301 NEW Implementing edit link on inline blocks and updating styling
  client/dist/js/bundle.js
  client/dist/styles/bundle.css
  client/src/components/ElementEditor/Element.js
  client/src/components/ElementEditor/Element.scss
  client/src/components/ElementEditor/ElementList.js
  client/src/components/HistoricElementView/tests/HistoricElementView-test.js
  src/Models/BaseElement.php
Labels: affects/v4, change/minor

#310 API Bump minimum SilverStripe version to 4.3 and implement multi-schema GraphQL support
  .travis.yml
  _config/graphql.yml
  composer.json
Labels: affects/v4, change/minor

#313 NEW Block schema is now extensible, getBlockSchema marked as internal
  src/Models/BaseElement.php
  src/Models/ElementContent.php
Labels: affects/v4, change/minor

#303 FIX Use LatestDraftVersion in GraphQL query to determine latest draft version
  client/dist/js/bundle.js
  client/src/state/history/readOneBlockQuery.js
Labels: affects/v4, change/patch

#314 NEW Elements can be deleted via the inline delete button. Fix versioning state in readBlocks query
  _config/graphql.yml
  client/dist/js/bundle.js
  client/dist/styles/bundle.css
  client/src/components/ElementEditor/Element.js
  client/src/components/ElementEditor/Element.scss
  client/src/components/ElementEditor/Header.js
  client/src/components/ElementEditor/tests/Header-test.js
  client/src/state/editor/deleteBlockMutation.js
  client/src/state/editor/readBlocksForPageQuery.js
Labels: affects/v4, change/minor

#316 FIX ElementList shows loading indicator while GraphQL query fetches list of blocks
  client/dist/js/bundle.js
  client/dist/styles/bundle.css
  client/src/components/ElementEditor/Element.scss
  client/src/components/ElementEditor/ElementList.js
  client/src/components/ElementEditor/ElementList.scss
Labels: affects/v4, change/patch

#319 Fix infinite loop on write
  src/Models/ElementalArea.php
Labels: affects/v4, change/patch

#315 Adjust spacing for element list element header
  .eslintrc.js
  .sass-lint.yml
  client/dist/js/bundle.js
  client/dist/styles/bundle.css
  client/src/components/ElementEditor/AddNewButton.scss
  client/src/components/ElementEditor/Content.js
  client/src/components/ElementEditor/Content.scss
  client/src/components/ElementEditor/Element.scss
  client/src/components/ElementEditor/Header.scss
  client/src/components/ElementEditor/tests/Content-test.js
  client/src/styles/history.scss
  package.json
  yarn.lock
Labels: affects/v4, change/patch

#342 fix(ElementalPageExtension): Update getElementsForSearch() so that it…
  src/Controllers/ElementSiteTreeFilterSearch.php
  src/Extensions/ElementalPageExtension.php
Labels: affects/v4, change/patch

#348 FIX Restore write to getOwnerPage and prevent write recursion
  src/Models/ElementalArea.php
Labels: affects/v4, change/patch

#346 NEW In-line edit is an opt-out configuration setting
  README.md
  _config/graphql.yml
  client/dist/js/bundle.js
  client/src/types/elementType.js
  src/Models/BaseElement.php
Labels: affects/v4, change/minor

#345 ENH Add action dropdown. Move delete button.
  client/dist/js/bundle.js
  client/dist/styles/bundle.css
  client/src/components/ElementEditor/Header.js
  client/src/components/ElementEditor/Header.scss
  tests/Behat/Context/FeatureContext.php
  tests/Behat/features/element-editor.feature
Labels: affects/v4, change/minor

#349 Re-enable Postgres in Travis build matrix
  .travis.yml
  tests/ElementalEditorTest.php
  tests/ElementalEditorTest.yml
Labels: affects/v4, change/patch

#352 FIX Give add new element dropdown class necessary to remove rounded corners when in input group
  client/dist/js/bundle.js
  client/src/components/ElementEditor/AddNewButton.js
Labels: affects/v4, change/patch

#356 NEW Inline editable prop now controls whether you can toggle edit mode
  client/dist/js/bundle.js
  client/dist/styles/bundle.css
  client/src/components/ElementEditor/Element.js
  client/src/components/ElementEditor/Element.scss
  client/src/components/ElementEditor/Header.js
  client/src/components/ElementEditor/Header.scss
  client/src/components/ElementEditor/tests/Header-test.js
Labels: affects/v4, change/minor

#359 Update ElementalAreasExtension example code
  src/Extensions/ElementalAreasExtension.php
Labels: affects/v4, type/docs

#357 FIX Resolving various console warning
  client/dist/js/bundle.js
  client/src/components/ElementEditor/AddNewButton.js
  client/src/components/ElementEditor/Header.js
  client/src/components/ElementEditor/tests/Element-test.js
  client/src/components/ElementEditor/tests/Header-test.js
  client/src/types/elementType.js
Labels: affects/v4, change/patch

#360 NEW Elements can be published via the inline publish button
  _config/graphql.yml
  client/dist/js/bundle.js
  client/src/components/ElementEditor/Element.js
  client/src/components/ElementEditor/Header.js
  client/src/state/editor/publishBlockMutation.js
  client/src/state/editor/readBlocksForPageQuery.js
  client/src/types/elementType.js
  src/Models/BaseElement.php
Labels: affects/v4, type/enhancement

#363 NEW Rename delete button to archive button. Update all references.
  client/dist/js/bundle.js
  client/src/components/ElementEditor/Header.js
  client/src/state/editor/archiveBlockMutation.js
  tests/Behat/Context/FeatureContext.php
  tests/Behat/features/element-editor.feature
Labels: affects/v4, change/minor
