Repository silverstripe/silverstripe-elemental, pull requests merged in 2018-06, with the labels that each got.

#231 NEW Add extension to activate history viewer when blocks pages are being viewed
  _config/extensions.yml
  client/dist/js/bundle.js
  client/src/bundles/BlockHistory.js
  client/src/bundles/bundle.js
  src/Extensions/CMSPageHistoryViewerControllerExtension.php
Labels: affects/v4, change/minor

#237 API Fix controller factory extension name and class it extends
  _config/extensions.yml
  src/Extensions/HistoryControllerFactoryExtension.php
Labels: affects/v4, change/major

#246 Update README.md
  README.md
Labels: type/docs

#244 API Remove deprecated duplication extension, remove unneeded write() calls and improve some doc blocks
  src/Extensions/ElementalAreasExtension.php
  src/Extensions/ElementalDuplicationExtension.php
  src/Models/BaseElement.php
  tests/ElementalAreaTest.php
Labels: affects/v4, change/major

#248 FIX Error loading history view with Banner Block, now passes form to child form fields
  src/Forms/ElementalAreaField.php
Labels: affects/v4, change/patch

#250 DOCS Rename docs folder to _images and update links as required
  docs/en/userguide/_images/block_version.png
  docs/en/userguide/_images/content-block-overview.png
  docs/en/userguide/_images/creating_a_content_block.png
  docs/en/userguide/_images/edit_via_more_actions.png
  docs/en/userguide/_images/editing_content.png
  docs/en/userguide/_images/reordering_blocks.png
  docs/en/userguide/_images/report_in_use.png
  docs/en/userguide/_images/report_types.png
  docs/en/userguide/_images/revert_button.png
  docs/en/userguide/_images/viewing_block_history.png
  docs/en/userguide/edit_content.md
  docs/en/userguide/history.md
  docs/en/userguide/reports.md
Labels: affects/v4, type/docs
