Repository silverstripe/silverstripe-elemental, pull requests merged in 2019-02, with the labels that each got.

#571 Open virtual link in a new window
  code/models/ElementVirtualLinked.php
Labels: affects/v3, change/patch

#596 FIX Updating behat tests to not specifically mention page ID
  tests/Behat/features/add-block-element.feature
  tests/Behat/features/archive-block-element.feature
  tests/Behat/features/edit-block-element.feature
  tests/Behat/features/element-editor.feature
  tests/Behat/features/empty-element-list.feature
  tests/Behat/features/publish-block-element.feature
  tests/Behat/features/unpublish-block-element.feature
Labels: affects/v4, change/patch

#587 FIX Implementing custom read resolver to fix permission issue
  _config/graphql.yml
  src/GraphQL/ReadOneAreaResolver.php
  tests/Behat/features/element-editor.feature
Labels: affects/v4, change/patch

#597 FIX Ensuring state is destroyed correctly & updating publish action
  client/dist/js/bundle.js
  client/src/components/ElementActions/PublishAction.js
  client/src/legacy/ElementEditor/entwine.js
Labels: affects/v4, change/patch

#602 FIX ElementalAreas should not be shown as part of implicit changesets in campaign admin
  src/Models/ElementalArea.php
Labels: affects/v4, change/patch

#601 FIX Element type is now passed to actions components so they can use the "title" for toast messages
  client/dist/js/bundle.js
  client/src/components/ElementActions/AbstractAction.js
  client/src/components/ElementActions/PublishAction.js
  client/src/components/ElementActions/SaveAction.js
  client/src/components/ElementActions/UnpublishAction.js
  client/src/components/ElementActions/tests/UnpublishAction-test.js
  client/src/components/ElementEditor/ElementActions.js
  client/src/components/ElementEditor/Header.js
  client/src/components/ElementEditor/tests/ElementActions-test.js
Labels: affects/v4, change/patch

#604 Hotfix/require default records
  src/Extensions/ElementalAreasExtension.php
Labels: affects/v4, change/patch

#610 FIX Ensuring drag events do not start an element reorder drag when the target is an inline edit form
  client/dist/js/bundle.js
  client/src/components/ElementActions/SaveAction.js
  client/src/components/ElementEditor/Element.js
  client/src/components/ElementEditor/Header.js
  client/src/components/ElementEditor/tests/Header-test.js
  client/src/lib/dragHelpers.js
Labels: affects/v4, change/major

#616 Remove coupling between ElementalArea and SiteTree
  src/Models/ElementalArea.php
Labels: affects/v4, change/patch

#623 FIX Assert elemental areas exist before calling methods on them
  src/GraphQL/ReadOneAreaResolver.php
Labels: affects/v4, change/patch
