Repository silverstripe/silverstripe-elemental, pull requests merged in 2019-08, with the labels that each got.

#701 NEW Page level history now links directly into an elements history view
  client/dist/js/bundle.js
  client/lang/src/en.json
  client/src/components/HistoricElementView/HistoricElementView.js
  client/src/components/HistoricElementView/tests/HistoricElementView-test.js
  src/Forms/ElementalAreaField.php
  src/Models/BaseElement.php
  tests/BaseElementTest.php
Labels: affects/v4, change/minor

#711 API Deprecate ElementalSolrIndex
  src/Search/ElementalSolrIndex.php
Labels: affects/v4, change/minor

#712 API Remove ElementalSolrIndex
  README.md
  docs/en/searching-blocks.md
  src/Search/ElementalSolrIndex.php
Labels: affects/v4, change/major

#717 FIX Reorder block actions
  client/dist/js/bundle.js
  client/src/boot/registerTransforms.js
Labels: affects/v4, change/patch

#719 FIX Restore the statusbar to TinyMCE in blocks (and the drag handle with it)
  src/Forms/EditFormFactory.php
Labels: affects/v4, change/patch

#721 FIX Remove pagination on blocks so more than 100 blocks appear in editor
  _config/graphql.yml
  client/dist/js/bundle.js
  client/src/components/ElementActions/PublishAction.js
  client/src/state/editor/readBlocksForAreaQuery.js
  client/src/state/editor/sortBlockMutation.js
Labels: affects/v4

#710 DOCS Searching blocks
  README.md
  docs/en/searching-blocks.md
Labels: affects/v4, type/docs

#724 Make the HoverBar more visible
  client/dist/js/bundle.js
  client/dist/styles/bundle.css
  client/src/components/ElementEditor/ElementList.js
  client/src/components/ElementEditor/HoverBar.js
  client/src/components/ElementEditor/HoverBar.scss
  client/src/lib/prefixClassNames.js
  client/src/lib/tests/prefixClassNames-test.js
Labels: affects/v4, change/minor

#727 BUG Remove unused method from AddElementPopover
  client/dist/js/bundle.js
  client/src/components/ElementEditor/AddElementPopover.js
  client/src/components/ElementEditor/HoverBar.js
Labels: affects/v4, change/patch
